language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISRY_TOKEN
  - secure: F+3QL+wwxByekGLsrARVWfznESdItgVmYN5vZQddTTnl4aMvgZebkyPGIVpmqQh1AqEmlbaF2mIq2fzbMF9XAmAJm0zbxYxxUkFyLTzH6eQ36BBN9QFCNuIBTg6JjqJ1YH/72xQMiUO1WsyCqC48hb2t0+m9qMBGZejwqtBh7cUMFXLGQtLsZ4C+5UVmfT+cusjBY/i4ycE1t/E4358y599KPr/vLHy+lwnOv9tOEYckseYH9befbjkuvYJNHcT70/zQpogQy7oRiLtMfLIqfcJ+7Isx8ZxIxSRBWAFmW2ww6r4w7CxJqice4WC2B7HxEB799qIV3s6Bie2zhD2SRQQqLboppnorkpUvS1FouhhX8iJYIj6PhQjsZSJmlA+/sJAkgSicBJI8TMDhSBLiPQrsSud1vUAtRsIywHZPy6jK75+yXamfDGb4iD/EMJbG4UcGORiuLEv5OTp1ih/rI3eenks2x0XmwG5/fU0UCQrvPUTjGGwcean4jRtd/7BsQcef2Rf1zgxKjwnSrxkFsTV5Bqv723asBLiym2scAr+T0qchbTUYWGTK/0/2eUOXRWOs1jkGBgBUwv476ymu7ZnpJmIhKIkN6Pf1tLKfe6+dIz7dNdr5dn2T5wEgOFwDq6N2hySmgJ3YWzhexjNC2LMOUJoe14qjEQEqzHRcdlU=
  # MATTERMOST_HOOK_URL
  - secure: y9chz5SHrjnEqX7Bu/XpcWDBBUEVYi2X+3cIgnQiOdk7h2LkWDxcNuUWhVckAhUihX2D4PfRfr3zxxG0V2QewzfGbyHqRoewpHDtpLqBfRZ5Id8VujeRC+jv5h0yGKrEBBRl+qYUsU2Al9RLC28rlnHJR7dGS8yPJnqst3gesK+GY9c0Z2JM4BXMlPnv4yX+pXpWOSIwycaqV25gl1GO+4Qc2znAdkg9OkdkrA/oT1YCysQ7IEwa02QKKcB7cAZnkl1nMGrfY66IrSWEoxfLApSQGUlVKgIh4NO+483KUWaDACzqxPeRHUmHz1c+Oam1a5E2iVqpAh5B08vbu6boTNWDDTjSX9Ake2I1Xm2Oojtc6/88+lY1gtJIUDaT/w1/p7e09dNoz+93MdnP/Shq2wCZFye8LjBnUUASRCt0N17Ixgl+jHLRzq6svTT74g+I7csaW9vPZmt3mOrxOrpBD/ENj9R3fxlztxBJIeB6dyhIPGcdc+ICkN/J3vjkewErsMXv1WTl0BSzBvYAVdQNs8vXkW5/g5OLMt+9v427WeKClR94otrH6PBSdOgurkap+mVSiWkEXAz2NCVNw8PEm7j3LN/3//CXPUfJxUPkYkTuIGnns91LDs7A0XZ4mVuHjJYsSOoVQw5Njt2LUahPlZplb91SUyRil4RppaMI4l8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
